import type { Metadata } from "next";
import AppLayout from "@/app/layouts/AppLayout";
export const metadata: Metadata = {
  title: "LafiaEMR Super admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AppLayout>{children}</AppLayout>;
}
