import type { Metadata } from "next";
// import "./globals.scss"
import AppProvider from "@/app/layouts/AppProvider";
import AppLayout from "@/app/layouts/AppLayout";
export const metadata: Metadata = {
  title: "LafiaEMR Super admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppLayout>
        {children}
      </AppLayout>
      </body>
    </html>
  );
}