import type { Metadata } from "next"

import AppProvider from "@/layouts/AppProvider"

import "./globals.scss"

export const metadata: Metadata = {
   title: "LafiaEMR Super Admin",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body>
            <AppProvider>{children}</AppProvider>
         </body>
      </html>
   )
}
