import type { Metadata } from "next";
import "./globals.scss";
import AppProvider from "@/layouts/AppProvider";

export const metadata: Metadata = {
  title: "LafiaEMR Super Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
